version: '2'

services:
  http1:
    image: http:1.0
    command: >
      9090 9070
    ports:
      - 8080:9070

#  http2:
#      image: http:1.0
#      command: >
#        9091 9075
#      ports:
#            - 8081:9075