version: '2'

services:
  http1:
    image: http:1.0
    command: >
      9090 1600
    ports:
      - "1600:1600"
      - "9090:9090"

#  http2:
#      image: http:1.0
#      command: >
#        9092 9075
#      ports:
#        - "8081:9075"
#
#      links: ["http1:akkaseed"]